services:
  app:
    container_name: hsbo-spring-demo-app
    networks:
      - default
    build: 
      context: ./service/app
      dockerfile: Dockerfile

  db:
    image: mongo:latest
    container_name: hsbo-spring-demo-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    networks:
      - default

  influx:
    image: influxdb:latest
    container_name: hsbo-spring-demo-influx
    env_file:
      - .env
    ports:
      - "8086:8086"
    volumes:
      - ./data/influx/data:/var/lib/influxdb2
      - ./data/influx/config:/etc/influxdb2
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: hsbo-spring-demo-grafana
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - influx

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: hsbo-spring-demo-mosquitto
    restart: unless-stopped
    networks:
      - default
    ports:
      - "1883:1883"
    volumes:
      - ./data/mosquitto:/mosquitto

  simulation-py:
    container_name: hsbo-spring-demo-simulation-py
    build:
      context: ./service/simulation-py
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - MQTT_USERNAME=martin.peth@stud.hs-bochum.de
      - MQTT_PASSWORD=018101006
    networks:
      - default
    depends_on:
      - mosquitto

volumes:
  mongodb-data: