services:
  app:
    container_name: hsbo-spring-demo-app
    networks:
      - default
    build: 
      context: ./service/app
      dockerfile: Dockerfile

  db:
    image: mongo:latest
    container_name: hsbo-spring-demo-db
    env_file:
      - .env
    ports:
        - "27017:27017"
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - default

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: hsbo-spring-demo-mosquitto
    restart: unless-stopped
    networks:
      - default
    ports:
      - "1883:1883"
    volumes:
      - ./data/mosquitto:/mosquitto

  simulation-py:
    container_name: hsbo-spring-demo-simulation-py
    build:
      context: ./service/simulation-py
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - default
    depends_on:
      - mosquitto

volumes:
  mongodb-data: